on:
  push:
    branches:
      - 'staging'

name: Docker build and push

env:
  IMAGE_REPOSITORY: quainetwork/quaiscan
  BACKEND_VERSION: "6.3.0"

jobs:
  push:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.PROTOFIRE_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PROTOFIRE_DOCKERHUB_TOKEN }}

      - name: Prepare image tag
        shell: bash
        run: |
          echo "IMAGE_TAG=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Build and push
        run: |
          docker build -t ${{ env.IMAGE_REPOSITORY }}:staging-${{ env.IMAGE_TAG }} \
          -t ${{ env.IMAGE_REPOSITORY }}:staging-latest \
          --build-arg BLOCKSCOUT_VERSION=v${{ env.BACKEND_VERSION }} \
          --build-arg RELEASE_VERSION=${{ env.BACKEND_VERSION }} \
          --build-arg DISABLE_WEBAPP=true \
          --build-arg ADMIN_PANEL_ENABLED=false \
          --build-arg CACHE_EXCHANGE_RATES_PERIOD= \
          --build-arg API_V1_READ_METHODS_DISABLED=false \
          --build-arg API_V1_WRITE_METHODS_DISABLED=false \
          --build-arg CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED=true \
          --build-arg DECODE_NOT_A_CONTRACT_CALLS=false \
          --build-arg CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL= \
          --build-arg CHAIN_TYPE=quai \
          --build-arg CHAIN_INDEX=2 \
          --cache-from blockscout/blockscout:buildcache \
          -f ./docker/Dockerfile .
          docker push ${{ env.IMAGE_REPOSITORY }} --all-tags
